require 'spree_core'
require 'spree_auth_devise'
require 'omniauth-twitter'
require 'omniauth-facebook'
require 'omniauth-github'
require 'omniauth-google-oauth2'
require 'omniauth-instagram'
require 'spree_social/engine'
